name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: sudo apt-get install -y g++-12 cmake
      
    - name: Build Example
      run: |
        g++-12 -std=c++20 -I include example/ex_phishing.cpp -o example/quick_start
        
    - name: Run Quick Start
      run: |
        cd example && ./quick_start